name: Deploy React Book App from GitHub to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2

      - name: Generate Deployment Package 
        run: zip -r BookAppFrontend.zip * -x "**.git**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: "${{ secrets.ACCESS_KEY }}"
          aws_secret_key: "${{ secrets.SECRET_ACCESS_KEY }}"
          application_name: NerdsHubApp
          environment_name: NerdsHubApp-env
          version_label: "app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: BookAppFrontend.zip

      - name: Deployed!
        run: echo App deployed to ELB
